[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_project"
version = "0.1.0"
dependencies = [
    "torch",
    "numpy",
    "matplotlib",
    "scipy",

]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "jupyter",
    "openTSNE",
    "pandas",
    "plotly",
    "nbformat",
]

[tool.setuptools]
packages = ["utils"]